### PR TITLE
Fix output of queried data.

### PR DESCRIPTION
**Pull request by malex984**
1. better YAML for complicated data containers)
2. no YAML output for simple data (e.g. strings)!

### CODE REVIEW

**Comment by malex984** [comment]
@porst17 note that booleans will be presented like in Python ('true' -> "True", 'false' -> "False")

**Comment by malex984** [comment]
@porst17 will only produce nice YAML output if explicitly asked for it with a suffix `all`!

**Comment by malex984** [comment]
Should be done now. Fixes #67

**Review by porst17 — APPROVED** [review]

**Comment by malex984** [comment]
also fixes #66

**Pull request merged**
